// Generated by CoffeeScript 1.6.3
(function() {
  var portfolioApp;

  portfolioApp = angular.module('portfolioApp', []);

  portfolioApp.controller('ProjectCtrl', function($scope, $http) {
    return $http.get('projects/projects.json').success(function(data) {
      return $scope.project = data;
    });
  });

}).call(this);
