// Generated by CoffeeScript 1.6.3
(function() {
  var portfolioApp, portfolioControllers;

  portfolioApp = angular.module('portfolioApp', ['ngRoute', 'portfolioControllers']);

  /* App Module*/


  portfolioApp.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/projects/:projectid', {
        templateUrl: '/partials/project_template.html',
        controller: 'ProjectCtrl'
      }).when('/index', {
        templateUrl: '/partials/index_template.html',
        controller: 'IndexCtrl'
      }).otherwise({
        redirectTo: '/index'
      });
    }
  ]);

  /* Controllers*/


  portfolioControllers = angular.module('portfolioControllers', []);

  portfolioControllers.controller('ProjectCtrl', [
    '$scope', '$http', '$routeParams', function($scope, $http, $routeParams) {
      $scope.projectid = $routeParams.projectid;
      console.log($scope.projectid);
      return $http.get('projects/projects.json').success(function(data) {
        return $scope.project = data;
      });
    }
  ]);

  portfolioControllers.controller('IndexCtrl', [function($scope) {}]);

}).call(this);
